### ISSUE TITLE
Auth failure when using next-stats-action in private github project

### ISSUE THREAD

**Issue by dawsbot** [zeit/next-stats-action#3]
Hi folks! Thanks for a great product.

We'd love to track out NextJS bundles over time, so we're trying to incorporate this github action in our project. Unfortunately, the auth errors we're seeing are cryptic and I could use some help getting this working in our project:

## The Issue

`fatal: could not read Username for 'https://github.com': No such device or address`

![image](https://user-images.githubusercontent.com/3408480/75615010-b43f3d80-5b0c-11ea-8163-71ac341a261b.png)

<br />

## Repro Steps

1. Add a `.github/workflows/pull_request_stats.yml` file with contents:

```yml
on:
    pull_request:
        types: [opened, synchronize]

name: Generate Pull Request Stats

jobs:
    stats:
        name: PR Stats
        runs-on: ubuntu-latest
        steps:
            - uses: zeit/next-stats-action@master
              env:
                  PR_STATS_COMMENT_TOKEN: ${{secrets.PR_STATS_COMMENT_TOKEN}}
```

2. Set the `PR_STATS_COMMENT_TOKEN` in github secrets for our project. Token has the following permissions and is a personal access token on my account, which is an owner of the org in which the repo resides: 

![image](https://user-images.githubusercontent.com/3408480/75615074-7858a800-5b0d-11ea-821b-557c09e92403.png)

<br />

## Follow-up Questions:

Should we create a [real github app](https://developer.github.com/v3/guides/basics-of-authentication/) for this?

![image](https://user-images.githubusercontent.com/3408480/75615063-45aeaf80-5b0d-11ea-922d-3a39d6530dfc.png)

**Comment by ericclemmons** [comment]
@ijjk add `stats-config.js` to the `/test/.stats-app` folder (it's easy to miss):
> https://github.com/zeit/next.js/blob/canary/test/.stats-app/stats-config.js

I wonder how it knows about it though?
> https://github.com/zeit/next.js/blob/canary/.github/workflows/pull_request_stats.yml

**Comment by chrisrichard** [comment]
A bit of guidance around how we can use this to produce stats for our Next.js-based apps would be awesome!

**Comment by ijjk** [comment]
Hi, this is mainly meant for generating stats on the Next.js repo itself. It currently only looks for the test app in [these locations](https://github.com/zeit/next-stats-action/blob/86954a8037ba6707c120782f042b241724dc7445/src/constants.js#L10-L15). We put it [here](https://github.com/zeit/next.js/tree/canary/test/.stats-app) for Next.js. 

It does not work with private repositories currently as this isn't a requirement for Next.js' usage of it. There are some quirks with posting the comment also as GitHub actions doesn't provide a token to the action that can post the stats anymore. We had to use a WebHook that is triggered for the `check_run` to handle this properly so that we don't have to expose any tokens in an unsafe way. 

It could be tweaked to support private repos by adding authentication when cloning the repo although features would still be specific to Next.js' use case

**Comment by chrisrichard** [comment]
Thanks for the info.

>It currently only looks for the test app in these locations.

Great. `'./'` should work for most people

>It could be tweaked to support private repos by adding authentication when cloning the repo although features would still be specific to Next.js' use case

I'll try to put something together. Thoughts on doing something similar to what the standard checkout action does?
 
```
- name: Checkout private tools
  uses: actions/checkout@v2
  with:
    repository: my-org/my-private-tools
    token: ${{ secrets.GITHUB_TOKEN }}
    path: my-tools
```
>There are some quirks with posting the comment also as GitHub actions doesn't provide a token to the action that can post the stats anymore.

Could we do the same thing for the comment post - use a token that can be supplied from a secret?
